spring:
  datasource:
    url: jdbc:postgresql://postgres-sql:5432/demo_db ## vc substitui o laval pelo conteiner-name
##    url: jdbc:postgresql://localhost:5432/demo_db
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
       
